# Generated by Django 4.1.1 on 2022-11-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("wins", models.IntegerField()),
                ("loses", models.IntegerField()),
                ("total", models.IntegerField()),
                ("streak", models.IntegerField()),
                ("rank", models.DecimalField(decimal_places=2, max_digits=8)),
                ("eth_addy", models.CharField(max_length=42, unique=True)),
                ("in_challenge", models.BooleanField()),
            ],
        ),
    ]
