# Generated by Django 4.1.1 on 2022-11-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=" ", max_length=42),
        ),
    ]
