# Generated by Django 4.1.1 on 2022-11-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="rank",
            new_name="ranking",
        ),
    ]
