# Generated by Django 4.1.1 on 2022-11-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_rename_rank_user_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profileurl",
            field=models.CharField(
                default="https://imgur.com/gallery/GaJ8kUc", max_length=100
            ),
        ),
    ]
